name: Terraform Destroy

on:
  workflow_dispatch:   # Allows manual trigger from GitHub Actions
  push:
    branches:
      - destroy        # Optional: trigger when a "destroy" branch is pushed

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=derick-terraform-state-bucket" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-2" \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
